### ISSUE TITLE
Value SUB-set of Allergy value set CH:AllergyInt -- Allergies and Intolerance values for immunization (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [ehealthsuisse/ch-vacd#91]
ch.fhir.ig.ch-vacd#1.0.0 /ValueSet-ch-vacd-immunization-allergyintolerances-vs.html

Check if this value set can be somehow linked to the existing (drafted) Allergy Value Set of CH:AllergyIntolerances (e.g. just show /use a subset? right now not all values are included in the larger CH:AllergInt VS)

Annatina Foppa, eHealth Suisse

**Comment by ralych** [comment]
Removing the separation of sections with the same codesystem

**Comment by eHealth-Suisse** [comment]
The profile is now derived from CHAllergyIntolerance which is fine.
From the idea of a "subset" we have to refrain because there were several changes since september:

- CHAllergyIntolerance binding will not be to the findings (concept "Allergy to X") but on substance level. Therefore, the semantic hierarchies of the value sets are different from each other.
- Expert review says that we should not talk of "Allergies" but rather of "Adverse reactions" which is more correct -> leads to a further difference.
